minimumReleaseAgeExclude:
  - '@valbuild/cli@0.138.5'
  - '@valbuild/core@0.138.2'
  - '@valbuild/language-server@0.138.5'
  - '@valbuild/mcp@0.138.5'
  - '@valbuild/react@0.138.5'
  - '@valbuild/server@0.138.5'
  - '@valbuild/shared@0.138.4'
  - '@valbuild/tanstack@0.138.5'
  - '@valbuild/ui@0.138.5'
  - '@valbuild/tanstack-build@0.138.4'
