/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as ValRouteRouteImport } from './routes/val/route'
import { Route as DotwellKnownOauthProtectedResourceRouteImport } from './routes/[.]well-known.oauth-protected-resource'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteStyleguideRouteImport } from './routes/_site.styleguide'
import { Route as ApiMcpRouteImport } from './routes/api/mcp'
import { Route as ValIndexRouteImport } from './routes/val/index'
import { Route as ValSplatRouteImport } from './routes/val/$'
import { Route as SiteProductsSkuRouteImport } from './routes/_site.products.$sku'
import { Route as ApiValSplatRouteImport } from './routes/api/val.$'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ValRouteRoute = ValRouteRouteImport.update({
  id: '/val',
  path: '/val',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownOauthProtectedResourceRoute =
  DotwellKnownOauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteStyleguideRoute = SiteStyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => SiteRoute,
} as any)
const ApiMcpRoute = ApiMcpRouteImport.update({
  id: '/api/mcp',
  path: '/api/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ValIndexRoute = ValIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ValRouteRoute,
} as any)
const ValSplatRoute = ValSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ValRouteRoute,
} as any)
const SiteProductsSkuRoute = SiteProductsSkuRouteImport.update({
  id: '/products/$sku',
  path: '/products/$sku',
  getParentRoute: () => SiteRoute,
} as any)
const ApiValSplatRoute = ApiValSplatRouteImport.update({
  id: '/api/val/$',
  path: '/api/val/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/val': typeof ValRouteRouteWithChildren
  '/': typeof SiteIndexRoute
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/styleguide': typeof SiteStyleguideRoute
  '/api/mcp': typeof ApiMcpRoute
  '/val/$': typeof ValSplatRoute
  '/val/': typeof ValIndexRoute
  '/products/$sku': typeof SiteProductsSkuRoute
  '/api/val/$': typeof ApiValSplatRoute
}
export interface FileRoutesByTo {
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/styleguide': typeof SiteStyleguideRoute
  '/api/mcp': typeof ApiMcpRoute
  '/val/$': typeof ValSplatRoute
  '/': typeof SiteIndexRoute
  '/val': typeof ValIndexRoute
  '/products/$sku': typeof SiteProductsSkuRoute
  '/api/val/$': typeof ApiValSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/val': typeof ValRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof DotwellKnownOauthProtectedResourceRoute
  '/_site/styleguide': typeof SiteStyleguideRoute
  '/api/mcp': typeof ApiMcpRoute
  '/val/$': typeof ValSplatRoute
  '/_site/': typeof SiteIndexRoute
  '/val/': typeof ValIndexRoute
  '/_site/products/$sku': typeof SiteProductsSkuRoute
  '/api/val/$': typeof ApiValSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/val'
    | '/'
    | '/.well-known/oauth-protected-resource'
    | '/styleguide'
    | '/api/mcp'
    | '/val/$'
    | '/val/'
    | '/products/$sku'
    | '/api/val/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/.well-known/oauth-protected-resource'
    | '/styleguide'
    | '/api/mcp'
    | '/val/$'
    | '/'
    | '/val'
    | '/products/$sku'
    | '/api/val/$'
  id:
    | '__root__'
    | '/val'
    | '/_site'
    | '/.well-known/oauth-protected-resource'
    | '/_site/styleguide'
    | '/api/mcp'
    | '/val/$'
    | '/_site/'
    | '/val/'
    | '/_site/products/$sku'
    | '/api/val/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ValRouteRoute: typeof ValRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
  DotwellKnownOauthProtectedResourceRoute: typeof DotwellKnownOauthProtectedResourceRoute
  ApiMcpRoute: typeof ApiMcpRoute
  ApiValSplatRoute: typeof ApiValSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/val': {
      id: '/val'
      path: '/val'
      fullPath: '/val'
      preLoaderRoute: typeof ValRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof DotwellKnownOauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/styleguide': {
      id: '/_site/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof SiteStyleguideRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/mcp': {
      id: '/api/mcp'
      path: '/api/mcp'
      fullPath: '/api/mcp'
      preLoaderRoute: typeof ApiMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/val/': {
      id: '/val/'
      path: '/'
      fullPath: '/val/'
      preLoaderRoute: typeof ValIndexRouteImport
      parentRoute: typeof ValRouteRoute
    }
    '/val/$': {
      id: '/val/$'
      path: '/$'
      fullPath: '/val/$'
      preLoaderRoute: typeof ValSplatRouteImport
      parentRoute: typeof ValRouteRoute
    }
    '/_site/products/$sku': {
      id: '/_site/products/$sku'
      path: '/products/$sku'
      fullPath: '/products/$sku'
      preLoaderRoute: typeof SiteProductsSkuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/val/$': {
      id: '/api/val/$'
      path: '/api/val/$'
      fullPath: '/api/val/$'
      preLoaderRoute: typeof ApiValSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ValRouteRouteChildren {
  ValSplatRoute: typeof ValSplatRoute
  ValIndexRoute: typeof ValIndexRoute
}

const ValRouteRouteChildren: ValRouteRouteChildren = {
  ValSplatRoute: ValSplatRoute,
  ValIndexRoute: ValIndexRoute,
}

const ValRouteRouteWithChildren = ValRouteRoute._addFileChildren(
  ValRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteStyleguideRoute: typeof SiteStyleguideRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductsSkuRoute: typeof SiteProductsSkuRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteStyleguideRoute: SiteStyleguideRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductsSkuRoute: SiteProductsSkuRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ValRouteRoute: ValRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
  DotwellKnownOauthProtectedResourceRoute:
    DotwellKnownOauthProtectedResourceRoute,
  ApiMcpRoute: ApiMcpRoute,
  ApiValSplatRoute: ApiValSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
